=== TestSubject528491/chharvey/resume/resume.schema.json
{
  "$schema": "http://json-schema.org/schema#",
  "$id": "http://chharvey.github.io/resume/resume.schema.json",
  "title": "Resume",
  "description": "Resume of Christopher H. Harvey of Fairfax, VA.",
  "definitions": {},
  "type": "object",
  "required": ["contact"],
  "additionalProperties": false,
  "properties": {
    "contact": {},
    "skills": {},
    "positions": {},
    "degrees": {},
    "prodevs": {},
    "awards": {},
    "teams": {}
  }
}

=== TestSubject528491/chharvey/resume/resume.json
{
  "contact": [
    {
      "url"     : "tel:+17035072467",
      "octicon" : "octicon-device-mobile",
      "itemprop": "telephone",
      "content" : "(703) 507-2467"
    },
    {
      "url"     : "mailto:chrisharvey2pi@gmail.com",
      "octicon" : "octicon-mail",
      "itemprop": "email",
      "content" : "chrisharvey2pi@gmail.com"
    },
    {
      "url"     : "https://chharvey.github.io/",
      "octicon" : "octicon-home",
      "itemprop": "url",
      "content" : "chharvey.github.io"
    }
  ],
  "skills": {},
  "positions": {},
  "degrees": {},
  "prodevs": {},
  "awards": {},
  "teams": {}
}
